mod 'boxen',      '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'osx',        '0.0.1', :github_tarball => 'boxen/puppet-osx'
mod 'repository', '2.2.0', :github_tarball => 'boxen/puppet-repository'
mod 'stdlib',     '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'zsh',        '1.0.0', :github_tarball => 'boxen/puppet-zsh'
